# my global config
global:
  scrape_interval: 1m # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 1m # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).
  scrape_timeout: 45s 

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - /etc/prometheus/rules.yaml
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ["localhost:9090", "node-exporter:9100"]

  - job_name: "WebsiteMonitoring"
    metrics_path: /probe
    params:
      module: [http_2xx]
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 192.168.1.133:9115
    static_configs:
    - targets:
      - https://healthyseed.org/

  - job_name: "vo-servers"
    static_configs:
    - targets:
      - nginx01.visibleone.local:9100
      - vorp-db.visibleone.local:9100
      - air-rock.visibleone.local:9100
      - vorp-web.visibleone.local:9100
      - shopinone-dev.visibleone.local:9100
      labels:
        env: vo-prod

  - job_name: "vo-managed-cloud"
    static_configs:
    - targets:
      - mediq.com.hk:9100
      - getmatric-shop.hipp.com.hk:9100
      - getmatric-club.hipp.com.hk:9100
      - www.avsecoqa.com.hk:9100
      - www.avseco.com.hk:9100
      - www.alphacapital-group.com:9100
      - utpieces.com:9100
      - asiapack.com:9100

  - job_name: "client-managed-cloud"
    static_configs:
    - targets:
      - tamjai-intl.com:9100
      - tamjaimixian.com:9100
      - www.tjsamgor.com:9100
    - targets: ["18.143.23.152:9100"]
      labels:
        instance: beyondsleep.com.hk

  - job_name: "vo-db"
    static_configs:
    - targets: ['192.168.1.130:9104']
      labels:
        db: vorpdb
        env: prod

  - job_name: "Domain"
    metrics_path: /probe
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - target_label: __address__
      replacement: 192.168.1.133:9222 # domain_exporter address
    file_sd_configs:
    - files: 
      - ./targets/domains.yaml

  - job_name: Website
    metrics_path: /probe
    params:
      module: [http_2xx]
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 192.168.1.133:9115
    file_sd_configs:
    - files: 
      - ./targets/websites.yaml
      - ./targets/cloud-websites.yaml
      - ./targets/plesk-websites.yaml
      - ./targets/vo-websites.yaml
  - job_name: Apache
    static_configs:
      - targets: ['18.163.97.41:9117']
        labels: 
          alias: shop.hipp.com.hk 
