# alertmanager.yml

route:
  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait: 10s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 30s

  group_by:
    - 'instance'
  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 12h

  # A default receiver
  receiver: "RocketChat"

  # All the above attributes are inherited by all child routes and can
  # overwritten on each.
  routes:
    - receiver: "RocketChat"
      match_re:
        severity: critical|warning
      continue: true

    - receiver: "smtp"
      match_re:
        severity: critical|warning
      continue: true

receivers:
  - name: "smtp"
    email_configs:
    - smarthost: smtp.gmail.com:587
      to: miky@visibleone.com
      from: "visibleone.miky@gmail.com"
      auth_username: "visibleone.miky@gmail.com"
      auth_identity: "visibleone.miky@gmail.com"
      auth_password: "mpzv oitu hirz xsrw"
      send_resolved: true
  - name: "RocketChat"
    webhook_configs:
      - send_resolved: true
        url: 'https://project.visibleone.com/hooks/656ed833ddf1d012fd9582ef/nHDusYcjzRKgpTD5ht4dEF8jarcgotCuJWatE96NMhPH3tgL'
