modules:
  http_2xx:
    prober: http
    timeout: 1m
    http:
      preferred_ip_protocol: ip4
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200]  # Defaults to 2xx
      method: GET
      no_follow_redirects: false

