version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - /data/wordpress:/var/www/html  # Map host directory /data/wordpress to container directory /var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - /data/db:/var/lib/mysql  # Map host directory /data/db to container directory /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

